### ISSUE TITLE
Inference on my own video clips

### ISSUE THREAD

**Issue by heldJan** [OpenSportsLab/OSL-ActionSpotting#19]
Hello,

I was wondering if it is possible to perform inference on my own video?

Thank you!

**Comment by Tortoise17** [comment]
@SilvioGiancola is there any inference pipeline available to test the model  on customized video?

**Comment by SilvioGiancola** [comment]
Yes, you can run inference on a custom dataset containing your own video with this code: https://github.com/OpenSportsLab/OSL-ActionSpotting/blob/main/tools/infer.py

**Comment by Tortoise17** [comment]
@SilvioGiancola  I tried two ways, one is the config which picks the SoccerNet file structure, and other way with the command and its config as well as the error. Please if you can hint me where I am making mistake. I have also extracted the features `.npy` file for the inference to get the results of predicted labels from the given customized input video match. 

```
(ball_play) [u100250@machine26 OSL-ActionSpotting]$ python tools/infer.py  --weights weights/netvlad++/json_netvlad++_resnetpca512.py --cfg-options configs/learnablepooling/json_netvlad++_resnetpca512.py data/input/testing/match.mp4 
Traceback (most recent call last):
  File "/scratch/local2/u100250/OSL-ActionSpotting/tools/infer.py", line 161, in <module>
    main()
  File "/scratch/local2/u100250/OSL-ActionSpotting/tools/infer.py", line 43, in main
    args = parse_args()
  File "/scratch/local2/u100250/OSL-ActionSpotting/tools/infer.py", line 37, in parse_args
    args = parser.parse_args()
  File "/home/u100250/anaconda3/envs/ball_play/lib/python3.10/argparse.py", line 1833, in parse_args
    args, argv = self.parse_known_args(args, namespace)
  File "/home/u100250/anaconda3/envs/ball_play/lib/python3.10/argparse.py", line 1866, in parse_known_args
    namespace, args = self._parse_known_args(args, namespace)
  File "/home/u100250/anaconda3/envs/ball_play/lib/python3.10/argparse.py", line 2079, in _parse_known_args
    start_index = consume_optional(start_index)
  File "/home/u100250/anaconda3/envs/ball_play/lib/python3.10/argparse.py", line 2019, in consume_optional
    take_action(action, args, option_string)
  File "/home/u100250/anaconda3/envs/ball_play/lib/python3.10/argparse.py", line 1943, in take_action
    action(self, namespace, argument_values, option_string)
  File "/home/u100250/anaconda3/envs/ball_play/lib/python3.10/site-packages/mmengine/config/config.py", line 1840, in __call__
    key, val = kv.split('=', maxsplit=1)
ValueError: not enough values to unpack (expected 2, got 1)
```


Please if you can help me to fix and get the output.

**Comment by Tortoise17** [comment]
@SilvioGiancola  Just a quick question, can you guide me, dataset.test.path=/datasets/SoccerNet/ResNET_PCA512/test/annotations.json looking into the part of inference command, how to create `annotations.json `for the custom video? From which tool we can create for using this repo. I mean not manually.

**Comment by Tortoise17** [comment]
@SilvioGiancola  Basically, what I am trying to do is, like in your soccernet_dev_kit, there is CALF base architecture, and for that inference workflow is available which can extract fratures and using those, it generates the file which is equal to Labels_v2.json. and with this infer.py file, I want to extract the labels_v2.json using the netvlad++ netrvlad++. Still unsuccessful. If you can guide or hint.

**Comment by Tortoise17** [comment]
@SilvioGiancola  I tried the file generated by `CALF inference` from your working `SoccerNet-Dev-Kit`, named as `annotations`, for this but still the error is :

command line is 
`
(football) [u120332@machine1 OSL-ActionSpotting]$ python tools/infer.py  python tools/infer.py  --cfg-options configs/learnablepooling/json_netvlad++_resnetpca512.py   dataset.test.data_root=/scratch/local1/tmp/OSL-ActionSpotting/data/input/soccer_test dataset.test.path=/scratch/local1/tmp/OSL-ActionSpotting/annotations/annotations.json`

Generated resulting error is 
```

Traceback (most recent call last):
  File "/scratch/local1/tmp/OSL-ActionSpotting/tools/infer.py", line 161, in <module>
    main()
  File "/scratch/local1/tmp/OSL-ActionSpotting/tools/infer.py", line 43, in main
    args = parse_args()
  File "/scratch/local1/tmp/OSL-ActionSpotting/tools/infer.py", line 37, in parse_args
    args = parser.parse_args()
  File "/home/python/anaconda3/envs/football/lib/python3.10/argparse.py", line 1833, in parse_args
    args, argv = self.parse_known_args(args, namespace)
  File "/home/python/anaconda3/envs/football/lib/python3.10/argparse.py", line 1866, in parse_known_args
    namespace, args = self._parse_known_args(args, namespace)
  File "/home/python/anaconda3/envs/football/lib/python3.10/argparse.py", line 2079, in _parse_known_args
    start_index = consume_optional(start_index)
  File "/home/python/anaconda3/envs/football/lib/python3.10/argparse.py", line 2019, in consume_optional
    take_action(action, args, option_string)
  File "/home/python/anaconda3/envs/football/lib/python3.10/argparse.py", line 1943, in take_action
    action(self, namespace, argument_values, option_string)
  File "/home/python/anaconda3/envs/football/lib/python3.10/site-packages/mmengine/config/config.py", line 1840, in __call__
    key, val = kv.split('=', maxsplit=1)
ValueError: not enough values to unpack (expected 2, got 1)
```

Please just guide if I am missing some point.
